import { FC, useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ShoppingCart, Eye, Star } from 'lucide-react';
import { coreApiClient as apiClient } from '../utils/api';
import { useCart } from '../context/CartContext';

interface Product {
  id: number;
  name: string;
  description: string;
  priceMoreThan9: number;
  priceLessThan9: number;
  size: string;
  color: string;
  material: string;
  imageUrl: string;
  stockQuantity: number;
}

const ProductCard: FC<{ product: Product }> = ({ product }) => {
  const { addToCart } = useCart();
  const [quantity] = useState(1);

  const handleAddToCart = () => {
    addToCart({
      id: Math.random(), // In a real app, this would be generated by the server or a unique ID
      productId: product.id,
      name: product.name,
      price: quantity > 9 ? product.priceMoreThan9 : product.priceLessThan9,
      quantity: quantity,
      image: product.imageUrl,
      size: product.size,
      color: product.color,
    });
  };

  return (
    <div className="bg-white rounded-xl shadow-sm hover:shadow-md transition-shadow duration-300 border border-gray-100 overflow-hidden group">
      <div className="relative aspect-square overflow-hidden bg-gray-100">
        <img
          src={product.imageUrl || 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=60'}
          alt={product.name}
          className="object-cover w-full h-full group-hover:scale-110 transition-transform duration-500"
        />
        <div className="absolute top-2 right-2 flex flex-col space-y-2 opacity-0 group-hover:opacity-100 transition-opacity">
          <Link to={`/product/${product.id}`} className="p-2 bg-white rounded-full shadow-md hover:bg-gray-50 text-gray-600">
            <Eye className="h-5 w-5" />
          </Link>
          <button onClick={handleAddToCart} className="p-2 bg-white rounded-full shadow-md hover:bg-gray-50 text-gray-600">
            <ShoppingCart className="h-5 w-5" />
          </button>
        </div>
        {product.stockQuantity < 10 && (
          <span className="absolute top-2 left-2 bg-red-500 text-white text-[10px] font-bold px-2 py-1 rounded-full uppercase">
            Low Stock
          </span>
        )}
      </div>

      <div className="p-4">
        <div className="flex items-center justify-between mb-2">
          <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">{product.material}</span>
          <div className="flex items-center text-yellow-400">
            <Star className="h-3 w-3 fill-current" />
            <span className="text-xs font-semibold ml-1 text-gray-600">4.8</span>
          </div>
        </div>
        <Link to={`/product/${product.id}`} className="text-lg font-bold text-gray-800 hover:text-primary transition mb-2 block truncate">
          {product.name}
        </Link>
        <p className="text-sm text-gray-500 mb-4 line-clamp-2 h-10">{product.description}</p>
        
        <div className="flex items-end justify-between">
          <div className="flex flex-col">
            <span className="text-sm text-gray-400 line-through">₹{product.priceLessThan9 + 50}</span>
            <div className="flex items-baseline space-x-1">
              <span className="text-2xl font-black text-primary">₹{product.priceMoreThan9}</span>
              <span className="text-xs text-gray-500 font-medium">/pc (9+ qty)</span>
            </div>
          </div>
          <button 
            onClick={handleAddToCart}
            className="bg-primary text-white p-2 rounded-lg hover:bg-gray-800 transition shadow-sm"
          >
            <ShoppingCart className="h-5 w-5" />
          </button>
        </div>
      </div>
    </div>
  );
};

const ProductList: FC = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchProducts = async () => {
      try {
        const response = await apiClient.get('products');
        setProducts(response.data);
      } catch (err) {
        console.error('Failed to fetch products', err);
      } finally {
        setLoading(false);
      }
    };
    fetchProducts();
  }, []);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-96">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
      {products.map((product) => (
        <ProductCard key={product.id} product={product} />
      ))}
    </div>
  );
};

export default ProductList;
